// <auto-generated />
using EnglishTraining;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace EnglishTraining.Migrations
{
    [DbContext(typeof(WordContext))]
    partial class WordContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125");

            modelBuilder.Entity("EnglishTraining.models.VmSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("DailyRepeatAmount");

                    b.Property<int?>("DailyTimeAmount");

                    b.Property<string>("LearningLanguage");

                    b.HasKey("Id");

                    b.ToTable("Settings");
                });

            modelBuilder.Entity("EnglishTraining.VmCollocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AudioUrl");

                    b.Property<string>("Lang");

                    b.Property<DateTime>("NextRepeatDate");

                    b.Property<bool>("NotUsedToday");

                    b.HasKey("Id");

                    b.ToTable("Collocations");
                });

            modelBuilder.Entity("EnglishTraining.VmWord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("DailyReapeatCountForEng");

                    b.Property<int>("DailyReapeatCountForRus");

                    b.Property<bool>("FourDaysLearnPhase");

                    b.Property<int>("LearnDay");

                    b.Property<string>("Name_en");

                    b.Property<string>("Name_ru");

                    b.Property<DateTime>("NextRepeatDate");

                    b.Property<int>("RepeatIterationNum");

                    b.HasKey("Id");

                    b.ToTable("Words");
                });
#pragma warning restore 612, 618
        }
    }
}
